### ISSUE TITLE
'Patch' doesn't seem to be supported any more

### ISSUE THREAD

**Issue by evjan** [dlindahl/frenetic#7]
The readme mentions support for "GET, POST, PUT, PATCH, and DELETE", but when I try to issue a patch, I get the following error:

    NoMethodError: undefined method `patch' for #<Frenetic:0x007fdc2cb7f240>>

Using frenetic 0.0.12 with faraday 0.8.8 (both are the latest versions at the time of writing).

**Comment by dlindahl** [comment]
Fixed in 62804e0bd745ab58a6ef1bd0c6dcabdad288ef41
